### PR TITLE
Update screenshots in members page with slow operation changes

### PR DESCRIPTION
**Pull request by emrberk**

### CODE REVIEW

**Review by zhmaeff — APPROVED** [review]

**Comment by zhmaeff** [comment]
need to be backported to 5.5.0 branch?

**Review by rebekah-lawrence — APPROVED** [review]
LGTM

Note, it seems there is an issue currently with the site; please check with @oliverhowell before merging

**Comment by emrberk** [comment]
> need to be backported to 5.5.0 branch?

Yes.

**Comment by Sodik** [comment]
@emrberk Please compress images

**Comment by promanenko** [comment]
please backport to v/5.5 branch

**Pull request merged**
