### PR TITLE
CPO-46 Restructure, update, and improve content

### PR DESCRIPTION
**Pull request by JakeSCahill**
We want to backport these changes to `v/5.0`. Then, we will reapply a couple of merged PRs to `main` that apply only to 5.1 snapshot: https://github.com/hazelcast/management-center-docs/pull/125 and https://github.com/hazelcast/management-center-docs/pull/126

This PR includes redirects for any pages that were moved or renamed, so the in-app links should be unaffected. In any case, I've opened a PR to update the links to go to the correct location in-app when we can, rather than relying on redirects: https://github.com/hazelcast/management-center/pull/5160

### CODE REVIEW

**Comment by JakeSCahill** [comment]
We need to reapply the changes made in this commit: https://github.com/hazelcast/management-center-docs/commit/89235eb8885a3f07e866eded087bfc922b26d675

Basically instead of using Java in examples, use the `mc-start` script.

**Comment by JakeSCahill** [comment]
The Jobs pages need some updates - some leftover outdated screenshots.

**Comment by jgardiner68** [comment]
Great to see the improvements. Some tweaks needed:

- can we allow larger screenshot views in the 5.1 documentation?
- First screen shot on https://deploy-preview-135--frosty-curran-1fc0c4.netlify.app/management-center/5.1-snapshot/getting-started/user-interface.html does not show the full menus (which is what this page is about)
- In Toolbar section (link above), order the points to match the order of the toolbar, SQL Browser and User/DevMode is missing.  Logout is not available in devmode
-  Left menu Integrate, Cluster JMX should be tagged as Enterprise and should have a note at the top of the page
- Shouldn't Clustered REST be under Integrate along with JMX and Prometheus?
- Clusters -> Admin -> Cluster State is tagged as Enterprise but it is not an EE feature (requires Admin role)
- Clusters -> Admin -> CP Subsystem is not an EE feature (needs to be configured otherwise shows as Disabled)
- Clusters -> Admin -> Config Healthcheck is an EE feature and needs to be tagged as such
- Config Healthcheck needs to be added to the two lists of licensed features

**Comment by JakeSCahill** [comment]
> Great to see the improvements. Some tweaks needed:
> 
> * can we allow larger screenshot views in the 5.1 documentation?
> * First screen shot on https://deploy-preview-135--frosty-curran-1fc0c4.netlify.app/management-center/5.1-snapshot/getting-started/user-interface.html does not show the full menus (which is what this page is about)
> * In Toolbar section (link above), order the points to match the order of the toolbar, SQL Browser and User/DevMode is missing.  Logout is not available in devmode
> * Left menu Integrate, Cluster JMX should be tagged as Enterprise and should have a note at the top of the page
> * Shouldn't Clustered REST be under Integrate along with JMX and Prometheus?
> * Clusters -> Admin -> Cluster State is tagged as Enterprise but it is not an EE feature (requires Admin role)
> * Clusters -> Admin -> CP Subsystem is not an EE feature (needs to be configured otherwise shows as Disabled)
> * Clusters -> Admin -> Config Healthcheck is an EE feature and needs to be tagged as such
> * Config Healthcheck needs to be added to the two lists of licensed features

All done, thanks @jgardiner68 

We want to backport these changes to v/5.0. Then, we will reapply a couple of merged PRs to `main` that apply only 5.1 snapshot.

This PR includes redirects for any pages that were moved or renamed, so the in-app links should be unaffected. In any case, I think it would be best to update the links to go to the correct location in-app when we can, rather than relying on redirects.

**Review by erosb — APPROVED** [review]

**Pull request merged**
